#!/bin/bash
set -e

mkdir -p build
cd build

if [[ ! -z "$mpi" && "$mpi" != "nompi" ]]; then
  HDF5_ENABLE_PARALLEL=ON
else
  HDF5_ENABLE_PARALLEL=OFF
fi

# Configure step
cmake $CMAKE_ARGS \
      -D CMAKE_BUILD_TYPE:STRING=RELEASE \
      -D CMAKE_PREFIX_PATH:PATH=$PREFIX \
      -D CMAKE_INSTALL_PREFIX:PATH=$PREFIX \
      -D HDF5_BUILD_CPP_LIB:BOOL=ON \
      -D CMAKE_POSITION_INDEPENDENT_CODE:BOOL=ON \
      -D BUILD_SHARED_LIBS:BOOL=ON \
      -D BUILD_STATIC_LIBS:BOOL=OFF \
      -D ONLY_SHARED_LIBS:BOOL=ON \
      -D HDF5_BUILD_HL_LIB:BOOL=ON \
      -D HDF5_BUILD_TOOLS:BOOL=ON \
      -D HDF5_BUILD_HL_GIF_TOOLS:BOOL=ON \
      -D HDF5_ENABLE_Z_LIB_SUPPORT:BOOL=ON \
      -D HDF5_ENABLE_THREADSAFE:BOOL=ON \
      -D HDF5_ENABLE_ROS3_VFD:BOOL=ON \
      -D HDF5_ENABLE_SZIP_SUPPORT=ON \
      -D ALLOW_UNSUPPORTED:BOOL=ON \
      -D HDF5_TEST_EXAMPLES:BOOL=OFF \
      -D HDF5_ENABLE_PARALLEL:BOOL=${HDF5_ENABLE_PARALLEL} \
      ..

make -j${CPU_COUNT}
make install
