travis:
  secure:
    BINSTAR_TOKEN: fGtnAoPPUR/HoL3IE/s9S7wzols9ZvXlZPv4MkbZI9y4W1n5bFacov6ZhigBvj40Cn5o8nFHYJHLT4EEcaskp/FEOnAM3Y0yiZzwr9ZtdTTiuvm+8q4dfCpv3RrHyKrlIdxxIUkPxzDPlcR+OeO7ZuB4Wv7GR6be5UZfMvoL0tI2yVkLzbtDBGyaVARWBu+I+uyEAIlNGanRAdcNeXGEA1w+8Fe3p/HgCrmm6n4P4rnT+91C73zpcK5n37KWdfQVl6Jy7Vx4EdQEqi1fe0B6G8CmxH1qVVEVhSDXy7eK0bmhp/Dul+jT4YjEdMw5t01b/kj9NGsOo4iHBxKwWeJf4ht0im6xOvsAbf40eVk8dqLFhLCZa9ar0I08tOvTNI/Oo74oCJ4T10VZCfuTwrlh1PX33btPHaU2/5NkPvymEbe79R3NSifaOww3LdIGkEsISipq9Ay+kbOltlIvV8+w5iSVcenutX/GGzqrqGs/hfbOBwRqoEEGCYSuff0FjLO5vZKrCCamBDPMQOa88BB0ctWEZ0geAzbETuJUEWTcb2S8adG9QuJAIitZ9UVeIifJ8NdR0ktsP/IrBk/es+tt89onGX2VRgv+u/4MjNp/B3F7C58UQ/lvYYWdbS3vvyqpwiHjLEa2x93YBxbI7q2zbtihMFrpAVOLcXFRqZCimU0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
